### ISSUE TITLE
Not able to successfully complete the call back 

### ISSUE THREAD

**Issue by adutta14** [mstade/passport-google-oauth2#12]
Hello, 
I followed the steps given but as soon as i click on "Allow" after logging into my google account, it breaks with the below error:-

Error
    at D:\ASU\SER 517\Oauth_mstade\passport-google-oauth2\example\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (D:\ASU\SER 517\Oauth_mstade\passport-google-oauth2\example\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\ASU\SER 517\Oauth_mstade\passport-google-oauth2\example\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Any idea whats going wrong here.

Thanks,
Abhishek Dutta

**Comment by TheWillG** [comment]
I am having this exact same error:
2018-03-03T05:55:34.312957+00:00 app[web.1]: - Error
2018-03-03T05:55:34.312969+00:00 app[web.1]: -     at /app/node_modules/passport-google-oauth20/lib/strategy.js:95:21
2018-03-03T05:55:34.312971+00:00 app[web.1]: -     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
2018-03-03T05:55:34.312973+00:00 app[web.1]: -     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
2018-03-03T05:55:34.312977+00:00 app[web.1]: -     at emitNone (events.js:110:20)
2018-03-03T05:55:34.312979+00:00 app[web.1]: -     at IncomingMessage.emit (events.js:207:7)
2018-03-03T05:55:34.312981+00:00 app[web.1]: -     at endReadableNT (_stream_readable.js:1047:12)
2018-03-03T05:55:34.312983+00:00 app[web.1]: -     at _combinedTickCallback (internal/process/next_tick.js:102:11)
2018-03-03T05:55:34.312984+00:00 app[web.1]: -     at process._tickCallback (internal/process/next_tick.js:161:9)

 Has it been fixed yet?
